### ISSUE TITLE
Syntax Error while publishing

### ISSUE THREAD

**Issue by amitmpixentech** [pixijs/animate#138]
Hi All,

I have a complex Animate CC animation which I have converted to Pixi-Animate and then trying to publish for version2 (Pixi 6). But I am getting an error "instance 36 is redeclared". There is no other clue or hint about the error. I tried deleting some objects and then getting like "instance32 is redeclared". 

Did anyone face the same issue? Which causes this issue and how to resolve it. Any help would be really appreciated.

![image](https://github.com/pixijs/animate/assets/104749364/ffcc9365-8f9e-49b9-8eef-06ee2c2b0324)

**Comment by andrewstart** [comment]
This is during an attempt at previewing the animation, after the animation has been written, right? Could you give us the output animation to look at? You can email it to me if you need to keep it private.

**Comment by amitmpixentech** [comment]
No, this is while doing the publishing. It creates the atlas jsons and images but not the js file.

Kindly let me know your mail id so that I can send the output files.

Best regards,

Amit M
________________________________

**Comment by andrewstart** [comment]
If it isn't getting as far as writing a .js file to disk, then you'll have to send the source file so I can test it myself. My email is start.andrew[at]gmail.com.

**Comment by andrewstart** [comment]
Posting the result here for posterity: Mask layers need to have only a single shape on them; Animate will duplicate masked content for each shape present in the mask. If you have multiple keyframes in a mask layer, masked content may also get duplicated between frames (or cause this same issue, I don't recall what happened the last time I came across that).
